// Code generated by Kitex v0.10.3. DO NOT EDIT.

package validateservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	validate "productshop/kitex_gen/shop/validate"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetValidate(ctx context.Context, req *validate.GetValidateReq, callOptions ...callopt.Option) (r *validate.GetValidateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kValidateServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kValidateServiceClient struct {
	*kClient
}

func (p *kValidateServiceClient) GetValidate(ctx context.Context, req *validate.GetValidateReq, callOptions ...callopt.Option) (r *validate.GetValidateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetValidate(ctx, req)
}
