// Code generated by Kitex v0.10.3. DO NOT EDIT.
package validateservice

import (
	server "github.com/cloudwego/kitex/server"
	validate "productshop/kitex_gen/shop/validate"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler validate.ValidateService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler validate.ValidateService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
